### ISSUE TITLE
Plugins shall migrate existing file nodes instead of creating new ones

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-plugins#59] opened 2018-01-29 12:33 UTC
Currently the plugin implementations create new `File` labeled nodes instead of using the ones already provided by the file scanner:

```
    public JavaSourceDescriptor scan(final FileResource item, final String path, final Scope scope, final Scanner scanner) throws IOException {
        final Store store = scanner.getContext().getStore();
        final JavaSourceFileDescriptor javaSourceFileDescriptor = store.create(JavaSourceFileDescriptor.class);
        javaSourceFileDescriptor.setFileName(path);
```

Instead the following pattern should be used:

```
@ScannerPlugin.Requires(FileDescriptor.class)
public class JavaparserScannerPlugin extends AbstractScannerPlugin<FileResource, JavaSourceDescriptor> {

....
    public JavaSourceDescriptor scan(final FileResource item, final String path, final Scope scope, final Scanner scanner) throws IOException {
        final Store store = scanner.getContext().getStore();
        FileDescriptor fileDescriptor = scanner.getContext().getCurrentDescriptor();
        final JavaSourceFileDescriptor javaSourceFileDescriptor = store.migrate(fileDescriptor, JavaSourceFileDescriptor.class);
...

**Comment by kontext-e** [comment] 2018-06-15 11:46
Will be in 1.4.1

**Comment by kontext-e** [comment] 2018-06-15 12:22
Did 'migrate' instead of 'create', but it does not work because Labels vanish. E.g. when the linecount plugin runs after this plugin (which accepts all files), there is only the Linecount label left.
Is this the expected behavior? I expected that all label accumulate instead replace. With current behavior 'migrate' is useless when several plugins run after each other.

**Comment by DirkMahler** [comment] 2018-06-15 12:32
Migrate is already heavily used by other plugins to add labels, see https://github.com/buschmais/jqa-java-plugin/blob/master/src/main/java/com/buschmais/jqassistant/plugin/java/impl/scanner/PropertyFileScannerPlugin.java#L41

**Comment by kontext-e** [comment] 2018-06-15 13:07
Ah, but this is 'addDescriptorType' which I expect to work like desired. Will give it a try.

**Comment by kontext-e** [comment] 2018-06-16 07:34
Seems to work as expected this time.

**Closed by kontext-e** 2018-06-16 07:34 UTC
